FROM python:slim-bookworm

WORKDIR /app/api/

COPY . . 

RUN pip install -r requirements.txt

EXPOSE 8000

ENV URL_ADDRESS="https://ec2-3-80-167-195.compute-1.amazonaws.com"

CMD ["uvicorn", "server:fastapi" ,  "--host"  ,"0.0.0.0",  "--port" , "8000"]