FROM python:slim-bookworm

ENV PYTHONBUFFERED 1
WORKDIR /app/api/

RUN python -m venv /opt/venv

# Enable venv
ENV PATH="/opt/venv/bin:$PATH"
ARG PUBLIC_HOSTING
COPY requirements.txt /app/api/requirements.txt 
RUN pip install -r requirements.txt
COPY . /app/api/ 
EXPOSE 8000
CMD uvicorn server:fastapi   --host  ${PUBLIC_HOSTING}  --port  8000
