FROM python:slim-bookworm

WORKDIR /app/api/
COPY ./requirements.txt  .

RUN pip install -r requirements.txt

COPY . . 

EXPOSE 8000

ARG URL_ADDRESS

CMD ["fastapi", "run" ,  "--host"  , ${URL_ADDRESS},  "--port" , "8000",    "/app/api/server.py" ]