services:
  api:
    image: devextralabs/extrasurface-api-server
    build:
      context: ./backend/api/
      dockerfile: Dockerfile.api
      args:
        - URL_ADDRESS="http://${LOCAL_IP}.compute-1.amazonaws.com:8000" ##TODO: define using env var
    env_file: ".env"
    ports:
      - 8000:8000
    cap_add:
        - ALL
    volumes:
      - $HOME/.aws/credentials:/.aws/credentials:ro

  sparkling_washeur_core:
    image: devextralabs/distributed-delaunay-transformation
    build:
      context: ./backend/sparkling_washeur/
      dockerfile: ./src/docker/Dockerfile-base-Ubuntu-devel
    volumes:
      - ${HOME}/.aws/credentials:/.aws/credentials:ro
      - ${PWD}/backend/sparkling_washeur:/app/sparkling_washeur/:rw
    environment:
      - NB_PROC="4"
      - DDT_TRAITS="3"
  spark_cluster:
    build:
      context: ./backend/sparkling_washeur/
      dockerfile: Dockerfile.spark 
    volumes:
      - ${HOME}/.aws/credentials:/.aws/credentials:ro
      - ${PWD}/backend/sparkling_washeur:/app/sparkling_washeur/:rw
    depends_on:
      - sparkling_washeur_core

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      - api
      - website
  website:
    image: devextralabs/website-frontend
    build: 
      context: ./frontend/
      dockerfile: dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api