services:
  api:
    image: devextralabs/extrasurface-api-server
    build:
      context: ./backend/sparkling_washeur/
      dockerfile: Dockerfile.api
    env_file: ".env"
    environment:
      - PUBLIC_HOSTING=${SERVER_IP}
    ports:
      - "8000:8000"
    expose:
      - 8000
    cap_add:
        - ALL
    volumes:
      - $HOME/.aws/credentials:/.aws/credentials:ro  

  sparkling_washeur_core:
    image: devextralabs/distributed-delaunay-transformation
    build:
      context: ./backend/sparkling_washeur/
      dockerfile: ./src/docker/Dockerfile-base-Ubuntu-devel
    volumes:
      - ${HOME}/.aws/:/.aws/:ro
    environment:
      - NB_PROC="4"
      - DDT_TRAITS="3"
 
networks:
  localhost_network:
    driver: bridge
    driver_opts:
      com.network.bridge.host_binding_ipv4:  ${SERVER_IP}
