version: '3.8'

services:
  sparkling_washeur:
    image: devextralabs/sparkling_washeur_algo
    build:
      context: ./backend/sparkling_washeur_algo
      dockerfile: Dockerfile.spark
    env_file: 
      - .env
    ports:
      - "8000:8000"
      - "7077:80"
    expose:
      - 8000 
      - 7077
    volumes:
      - $HOME/.aws/credentials:/.aws/credentials:ro  
      - ./example_data:/app/wasure/example_data ##TODO: remove this when we integrate the S3 bucket.
    command: ["bash", "/app/wasure/docker_interface.sh", "run_full_pipeline"]
  files_uploader:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/extralabs_file_handler
    env_file: 
      - .env
    build:
      context: backend/sparkling_wasure_serverless/lambda_services/files_uploader
      dockerfile: dockerfile

  email_sender:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/extrasurface/email_handling_service
    build:
      context: backend/sparkling_wasure_serverless/lambda_services/email_sender_service
      dockerfile: dockerfile

  events:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/extrasurface/events
    env_file: 
      - .env
    build:
      context: ./backend/sparkling_wasure_serverless/lambda_services/events
      dockerfile: dockerfile

  jobs_scheduler:
    env_file: 
      - .env
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/extrasurface/email_handling_service
    build:
      context: ./backend/sparkling_wasure_serverless/lambda_services/email_sender_service
      dockerfile: dockerfile
networks:
  localhost_network:
    driver: bridge
    driver_opts:
      com.network.bridge.host_binding_ipv4:  localhost


