services:
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile.api
    env_file: ".env"
    networks:
      - api
    cap_add:
        - ALL
  
  redis:
    image: redis:latest
    networks:
      - api
    ports:
      - "6379:6379"


  website:
    build: 
      context: ./ui/
      dockerfile: dockerfile
    networks:
      - api
      

networks:
  api:

  
