
FROM ubuntu:16.04

MAINTAINER Laurent Caraffa "caraffa.laurent@gmail.com"

#ENV http_proxy <HTTP_PROXY>
#ENV https_proxy <HTTPS_PROXY>
ENV http_proxy http://192.168.4.9:3128
ENV https_proxy http://192.168.4.9:3128



# Generals
RUN apt-get update &&  apt-get install -y cmake nano sudo gdb libboost-all-dev g++ wget  --assume-yes

#Lidar format dps
RUN apt-get update &&  apt-get install -y xsdcxx  libxerces-c-dev  --assume-yes

# Externs dps
RUN apt-get update &&  apt-get install -y libpng12-dev libjpeg-dev zlibc libxmu-dev libxi-dev freeglut3-dev libtiff5-dev  --assume-yes


# Matis-lib dps
RUN apt-get update &&  apt-get install -y libeigen3-dev   --assume-yes

# Scala
RUN  apt-get update &&  apt-get install -y scala --assume-yes


# Spark
RUN cd /usr/local/bin/ && \
    wget https://d3kbcqa49mib13.cloudfront.net/spark-2.2.0-bin-hadoop2.7.tgz && \
    wget https://github.com/sbt/sbt/releases/download/v1.0.0/sbt-1.0.0.tgz && \
    tar -xvf spark-2.2.0-bin-hadoop2.7.tgz && \
    tar -xvf sbt-1.0.0.tgz && \
    rm ./*gz

RUN apt-get update && apt-get install -y imagemagick --assume-yes

# CGAL and co
# libxerces-c-dev libxerces-c28
RUN apt-get update && apt-get -y install libcgal-qt5-dev libcgal-dev libxerces-c-dev  libboost-dev libtinyxml-dev libxerces-c-dev libann-dev --assume-yes


RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libcgal-dev



RUN mkdir /root/.ssh/


