FROM ddt_img_base

MAINTAINER Laurent Caraffa "caraffa.laurent@gmail.com"

RUN apt-get update &&  apt-get install -y  openjdk-8-jdk  --assume-yes
ENV JAVA_HOME "/usr/lib/jvm/java-8-openjdk-amd64/"

RUN cd /usr/local/bin/ && \
    wget https://archive.apache.org/dist/hadoop/core/hadoop-2.7.7/hadoop-2.7.7-src.tar.gz && \
    tar -xvf hadoop-2.7.7-src.tar.gz && \
    mkdir -p ./hadoop-2.7.7-src/hadoop-hdfs-project/hadoop-hdfs/src/build && \
    cd ./hadoop-2.7.7-src/hadoop-hdfs-project/hadoop-hdfs/src/build && \
    cmake ../ \
    make 



