FROM docker:dind as deploy 


# ARG NB_PROC="4"
# ARG DDT_TRAITS="3"

# WORKDIR /backend/sparkling_washeur
# COPY . . 

# RUN  ./src/docker/docker_interface.sh compile -`j + ${NB_PROC}` -`t + ${DDT_TRAITS}` && conda env create --file ./services/mesh23dtile/environment.yml && conda activate mesh23Dtile
