FROM python:slim-bookworm

WORKDIR /app/sparkling_washeur/

ARG PUBLIC_HOSTING
COPY requirements.txt /app/sparkling_washeur/requirements.txt 
RUN pip install -r requirements.txt
COPY . /app/sparkling_washeur/ 
EXPOSE 8000


CMD  uvicorn server:fastapi --host https://0.0.0.0:8000  --port  8000
