#define ANGLE_SCALE_2D (0.02)
#define ANGLE_SCALE_AERIAL_OLD (0.001)
#define ANGLE_SCALE_AERIAL (0.003)
#define ANGLE_SCALE_GROUND (0.005)
#define ANGLE_SCALE (ANGLE_SCALE_AERIAL)
#define GSPS_CONST (0.05)

#define NUM_ITER_TESSEL (10)
#define DIM_SIZE_NB (50)
