FIND_PATH(CUT-PURSUIT_INCLUDE_DIR API.h 
  ${EXTERN_PROJECT_SRC_DIR}/cut-pursuit/L0_cut_pursuit/include/

)


IF (CUT-PURSUIT_INCLUDE_DIR)
  SET(CUT-PURSUIT_INCLUDE_FOUND "YES")
  MESSAGE(STATUS "Found CUT-PURSUIT include dir: ${CUT-PURSUIT_INCLUDE_DIR}")
ENDIF (CUT-PURSUIT_INCLUDE_DIR)


IF(CUT-PURSUIT_INCLUDE_FOUND)
  SET(CUT-PURSUIT_FOUND "YES")
ENDIF(CUT-PURSUIT_INCLUDE_FOUND)
