Reading package lists...
Building dependency tree...
Reading state information...
python3-pip is already the newest version (9.0.1-2.3).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
