FROM public.ecr.aws/lambda/python:3.12


COPY requirements.txt ${LAMBDA_TASK_ROOT}

RUN pip install -r requirements.txt

# Copy function code
COPY app.py ${LAMBDA_TASK_ROOT}


CMD [ "app.email_sending_serverless" ]