FROM python:slim-bookworm as build

WORKDIR /app/api/

COPY ./api/requirements.txt  requirements.txt

RUN pip install -r requirements.txt

COPY . . 

EXPOSE 8001

CMD ["fastapi", "run" ,"/app/api/api/server.py" ]