name: Build and Test Scala Packages
on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Cache SBT dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Set up environment variables
        run: |
          echo "GITHUB_USERNAME=dhruvmalik007"
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Build and test backend/sparkling_washeur/src/spark
        working-directory: backend/sparkling_washeur/src/spark
        run: |
          sbt clean reload

      - name: Build and test backend/sparkling_washeur/services/wasure/workflow/workflow_preprocess
        working-directory: backend/sparkling_washeur/services/wasure/workflow/workflow_preprocess
        run: |
          sbt clean reload

      - name: Build and test backend/sparkling_washeur/services/wasure/workflow/workflow_wasure
        working-directory: backend/sparkling_washeur/services/wasure/workflow/workflow_wasure
        run: |
          sbt clean reload