name: Build and Test Scala Packages
on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - backend/sparkling_washeur/src/spark
          - backend/sparkling_washeur/services/wasure/workflow/workflow_preprocess
          - backend/sparkling_washeur/services/wasure/workflow/workflow_wasure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Cache SBT dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Build and test ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: |
          sbt clean compile test